//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertDestination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlertDestination()
        {
            this.AlertExecutions = new HashSet<AlertExecution>();
            this.AlertPendingExecutions = new HashSet<AlertPendingExecution>();
        }
    
        public int Id { get; set; }
        public int AlertTypeId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> CommandActivateId { get; set; }
        public Nullable<int> CommandDeactivateId { get; set; }
        public bool IsEnabled { get; set; }
        public int Priority { get; set; }
        public bool IsRemoved { get; set; }
        public Nullable<int> ElementId { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual Command Command1 { get; set; }
        public virtual Element Element { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertExecution> AlertExecutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertPendingExecution> AlertPendingExecutions { get; set; }
    }
}
