//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertPendingExecution
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public int AlertTypeId { get; set; }
        public System.DateTime UpdateTimestamp { get; set; }
        public Nullable<int> AlertDestinationId { get; set; }
        public string Header { get; set; }
        public string Message { get; set; }
        public bool IsWaitingOn { get; set; }
        public Nullable<System.DateTime> WaitOnEndDatetime { get; set; }
        public bool IsPendingToSend { get; set; }
        public bool IsSending { get; set; }
        public bool IsSent { get; set; }
        public bool IsSentOk { get; set; }
        public Nullable<System.DateTime> SentTimestamp { get; set; }
        public string SentResultMessage { get; set; }
        public int Retries { get; set; }
        public string RealDestination { get; set; }
        public Nullable<int> AlertStateId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AlertDestination AlertDestination { get; set; }
        public virtual Event Event { get; set; }
    }
}
