//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertPort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlertPort()
        {
            this.AlertParameterValues = new HashSet<AlertParameterValue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AlertTypeId { get; set; }
        public Nullable<int> PortId { get; set; }
        public bool IsEnabled { get; set; }
        public int Priority { get; set; }
        public int MaxRetries { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertParameterValue> AlertParameterValues { get; set; }
        public virtual Port Port { get; set; }
    }
}
