//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertTag
    {
        public int TagId { get; set; }
        public int AlertTypeId { get; set; }
        public bool AddHeaderElementName { get; set; }
        public bool AddHeaderTagClassDescription { get; set; }
        public bool AddHeaderTagName { get; set; }
        public bool AddHeaderState { get; set; }
        public string CustomHeader { get; set; }
        public bool AddElementName { get; set; }
        public bool AddTagClassDescription { get; set; }
        public bool AddTagName { get; set; }
        public bool AddState { get; set; }
        public string CustomMessage { get; set; }
        public bool AddFile { get; set; }
        public Nullable<int> AlertFileId { get; set; }
        public bool ConvertTextToVoice { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> OnWaitTime { get; set; }
    
        public virtual AlertFile AlertFile { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
