//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertParameterValue
    {
        public int AlertParameterId { get; set; }
        public int AlertPortId { get; set; }
        public Nullable<int> ValueInt { get; set; }
        public string ValueStr { get; set; }
        public Nullable<bool> ValueBool { get; set; }
    
        public virtual AlertPort AlertPort { get; set; }
    }
}
