//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertTemporarilyDisabled
    {
        public int Id { get; set; }
        public Nullable<int> ElementId { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public int AlertTypeId { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime StartTimestamp { get; set; }
        public System.DateTime EndTimestamp { get; set; }
        public System.DateTime UpdateTimestamp { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Element Element { get; set; }
    }
}
