//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Channel()
        {
            this.DeviceStates = new HashSet<DeviceState>();
            this.DeviceStates1 = new HashSet<DeviceState>();
            this.PortStates = new HashSet<PortState>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int MasterPortId { get; set; }
        public int SlavePortId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ProtocolId { get; set; }
    
        public virtual Port Port { get; set; }
        public virtual Port Port1 { get; set; }
        public virtual ChannelState ChannelState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceState> DeviceStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceState> DeviceStates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortState> PortStates { get; set; }
    }
}
