//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ChangeTypeId { get; set; }
        public int EntityId { get; set; }
        public string EntityName { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
        public System.DateTime UpdateTimestamp { get; set; }
    }
}
