//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandExecution
    {
        public int Id { get; set; }
        public int CommandId { get; set; }
        public int ValueEnumValueId { get; set; }
        public Nullable<int> TargetCommandId { get; set; }
        public Nullable<int> TargetValueEnumValueId { get; set; }
        public int StateEnumValueId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime ExpiresBy { get; set; }
        public Nullable<System.DateTime> SelectStart { get; set; }
        public Nullable<System.DateTime> Selected { get; set; }
        public Nullable<System.DateTime> ExecuteStart { get; set; }
        public Nullable<System.DateTime> Executed { get; set; }
        public Nullable<System.DateTime> Expired { get; set; }
        public Nullable<System.DateTime> Cancelled { get; set; }
        public Nullable<System.DateTime> SetByUser { get; set; }
        public bool IsFinished { get; set; }
        public Nullable<int> TagValueChangeId { get; set; }
        public System.DateTime UpdateTimestamp { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual TagValueChanx TagValueChanx { get; set; }
        public virtual Command Command1 { get; set; }
    }
}
