//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceState
    {
        public int DeviceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<System.DateTime> StateTimestamp { get; set; }
        public Nullable<int> RequestStateId { get; set; }
        public Nullable<System.DateTime> RequestStateTimestamp { get; set; }
        public Nullable<int> TransientStateId { get; set; }
        public Nullable<System.DateTime> TransientStateTimestamp { get; set; }
        public Nullable<System.DateTime> ExpiryDateTime { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<bool> IsConnected { get; set; }
        public string StatusMessage { get; set; }
        public Nullable<int> CurrentChannelId { get; set; }
        public Nullable<int> TransientChannelId { get; set; }
        public byte[] DatabaseBinaryFile { get; set; }
        public string DatabaseXmlFile { get; set; }
        public Nullable<System.DateTime> DatabaseGenerationTimestamp { get; set; }
        public string DatabaseServerXmlFile { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> LastConnection { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Channel Channel1 { get; set; }
        public virtual Device Device { get; set; }
    }
}
