//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.AlertTemporarilyDisableds = new HashSet<AlertTemporarilyDisabled>();
            this.CustomUserRights = new HashSet<CustomUserRight>();
            this.DevicePropertyValues = new HashSet<DevicePropertyValue>();
            this.Devices1 = new HashSet<Device>();
            this.Ports = new HashSet<Port>();
            this.Tags = new HashSet<Tag>();
            this.Tags1 = new HashSet<Tag>();
            this.TagSets = new HashSet<TagSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> Address { get; set; }
        public Nullable<int> SlaveNumber { get; set; }
        public string Comments { get; set; }
        public int DeviceTypeId { get; set; }
        public Nullable<int> ParentDeviceId { get; set; }
        public Nullable<int> ConnectionStateTagId { get; set; }
        public Nullable<int> ConnectionPetStateTagId { get; set; }
        public Nullable<int> ExportCode { get; set; }
        public Nullable<int> ExtensionPort1Type { get; set; }
        public Nullable<int> ExtensionPort2Type { get; set; }
        public Nullable<int> ExtensionPort3Type { get; set; }
        public bool IsAnalogMonopolar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertTemporarilyDisabled> AlertTemporarilyDisableds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomUserRight> CustomUserRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevicePropertyValue> DevicePropertyValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices1 { get; set; }
        public virtual Device Device1 { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual Tag Tag1 { get; set; }
        public virtual DeviceState DeviceState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Port> Ports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagSet> TagSets { get; set; }
    }
}
