//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.AlertExecutions = new HashSet<AlertExecution>();
            this.AlertPendingExecutions = new HashSet<AlertPendingExecution>();
        }
    
        public int Id { get; set; }
        public int TagValueChangeId { get; set; }
        public Nullable<int> AckUserId { get; set; }
        public Nullable<System.DateTime> AckTimestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertExecution> AlertExecutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertPendingExecution> AlertPendingExecutions { get; set; }
        public virtual TagValueChanx TagValueChanx { get; set; }
    }
}
