//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Network()
        {
            this.Controls = new HashSet<Control>();
            this.Controls1 = new HashSet<Control>();
            this.Networks1 = new HashSet<Network>();
            this.Nodes = new HashSet<Node>();
            this.Notes = new HashSet<Note>();
            this.Regions = new HashSet<Region>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int DefaultLayoutId { get; set; }
        public string BackgroundColor { get; set; }
        public string DefaultLineColor { get; set; }
        public bool IsElectrical { get; set; }
        public bool IsSnap { get; set; }
        public bool IsOrthogonal { get; set; }
        public int GridInterval { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public Nullable<int> ParentNetworkId { get; set; }
        public byte[] BackgroundImage { get; set; }
        public string BackgroundImageName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Control> Controls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Control> Controls1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Network> Networks1 { get; set; }
        public virtual Network Network1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Node> Nodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Region> Regions { get; set; }
    }
}
