//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodePolyline
    {
        public int Id { get; set; }
        public int PolylineId { get; set; }
        public int NodeId { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Polyline Polyline { get; set; }
    }
}
