//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodePosition
    {
        public int LayoutId { get; set; }
        public int NodeId { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public bool IsLabelVisible { get; set; }
        public Nullable<int> LabelX { get; set; }
        public Nullable<int> LabelY { get; set; }
    
        public virtual Node Node { get; set; }
    }
}
