//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.NotePositions = new HashSet<NotePosition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsEnabled { get; set; }
        public int NoteTypeId { get; set; }
        public int NetworkId { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
        public Nullable<System.DateTime> DeleteTimeStamp { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
    
        public virtual Network Network { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotePosition> NotePositions { get; set; }
    }
}
