//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortState
    {
        public int PortId { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> TransientChannelId { get; set; }
        public string StatusMessage { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> UpdateTimestamp { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Port Port { get; set; }
    }
}
