//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Port
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Port()
        {
            this.AlertPorts = new HashSet<AlertPort>();
            this.Channels = new HashSet<Channel>();
            this.Channels1 = new HashSet<Channel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Comments { get; set; }
        public int DeviceId { get; set; }
        public Nullable<int> Address { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> IpPort { get; set; }
        public Nullable<int> IpModeId { get; set; }
        public string Uri { get; set; }
        public Nullable<int> ProtocolId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public bool IsMaster { get; set; }
        public int Priority { get; set; }
        public Nullable<int> AppAddress { get; set; }
        public Nullable<int> OriginatorAddress { get; set; }
        public Nullable<int> ProtocolTimeout0 { get; set; }
        public Nullable<int> ProtocolTimeout1 { get; set; }
        public Nullable<int> ProtocolTimeout2 { get; set; }
        public Nullable<int> ProtocolTimeout3 { get; set; }
        public Nullable<int> DriverTimeout0 { get; set; }
        public Nullable<int> DriverTimeout1 { get; set; }
        public Nullable<int> DriverTimeout2 { get; set; }
        public Nullable<int> DriverTimeout3 { get; set; }
        public Nullable<int> Retries { get; set; }
        public string ExportPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertPort> AlertPorts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Channel> Channels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Channel> Channels1 { get; set; }
        public virtual Device Device { get; set; }
        public virtual PortState PortState { get; set; }
        public virtual SerialPort SerialPort { get; set; }
    }
}
