//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialPort
    {
        public int PortId { get; set; }
        public string LocalName { get; set; }
        public int SerialModeId { get; set; }
        public int BaudRate { get; set; }
        public int DataBits { get; set; }
        public int SerialParityId { get; set; }
        public double StopBits { get; set; }
        public string AtInitialize1 { get; set; }
        public string AtInitialize2 { get; set; }
        public string AtDialUp { get; set; }
        public string AtAnswer { get; set; }
        public string AtHangUp { get; set; }
        public string AtCommandMode { get; set; }
        public string PhoneNumber { get; set; }
        public string CcPhoneNumber { get; set; }
        public string ResponseOk { get; set; }
        public string ResponseConnect { get; set; }
        public string ResponseRing { get; set; }
        public Nullable<double> CtsWaitTime { get; set; }
        public Nullable<double> RtsStartWaitTime { get; set; }
        public Nullable<double> RtsEndWaitTime { get; set; }
    
        public virtual Port Port { get; set; }
    }
}
