//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagIntervalSummary
    {
        public int Id { get; set; }
        public int TagId { get; set; }
        public Nullable<double> StartValue { get; set; }
        public Nullable<System.DateTime> StartTimestamp { get; set; }
        public Nullable<double> EndValue { get; set; }
        public Nullable<System.DateTime> EndTimestamp { get; set; }
        public Nullable<int> IntervalTime { get; set; }
        public Nullable<double> MaximumValue { get; set; }
        public Nullable<System.DateTime> MaximumTimestamp { get; set; }
        public Nullable<double> MinimumValue { get; set; }
        public Nullable<System.DateTime> MinimumTimestamp { get; set; }
        public Nullable<double> AverageValue { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public Nullable<int> SampleCount { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> UpdateTimestamp { get; set; }
    
        public virtual Tag Tag { get; set; }
    }
}
