//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagPropertyValue
    {
        public int PropertyId { get; set; }
        public int TagId { get; set; }
        public string Value { get; set; }
        public Nullable<bool> ValueBool { get; set; }
        public Nullable<int> ValueInt { get; set; }
        public Nullable<double> ValueFloat { get; set; }
    
        public virtual Tag Tag { get; set; }
    }
}
