//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedisNetDataSimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagScale
    {
        public int Id { get; set; }
        public int TagId { get; set; }
        public double InputValue { get; set; }
        public double ResultValue { get; set; }
        public string Comments { get; set; }
    
        public virtual Tag Tag { get; set; }
    }
}
