//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp10.AdminCoreServiceTestReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Sitel.TedisNet.Admin.AdminService", ConfigurationName="AdminCoreServiceTestReference.IAdminCoreService")]
    public interface IAdminCoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sitel.TedisNet.Admin.AdminService/IAdminCoreService/MyTestMethod", ReplyAction="http://Sitel.TedisNet.Admin.AdminService/IAdminCoreService/MyTestMethodResponse")]
        int MyTestMethod(int data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sitel.TedisNet.Admin.AdminService/IAdminCoreService/MyTestMethod", ReplyAction="http://Sitel.TedisNet.Admin.AdminService/IAdminCoreService/MyTestMethodResponse")]
        System.Threading.Tasks.Task<int> MyTestMethodAsync(int data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminCoreServiceChannel : ConsoleApp10.AdminCoreServiceTestReference.IAdminCoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminCoreServiceClient : System.ServiceModel.ClientBase<ConsoleApp10.AdminCoreServiceTestReference.IAdminCoreService>, ConsoleApp10.AdminCoreServiceTestReference.IAdminCoreService {
        
        public AdminCoreServiceClient() {
        }
        
        public AdminCoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminCoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminCoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminCoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int MyTestMethod(int data) {
            return base.Channel.MyTestMethod(data);
        }
        
        public System.Threading.Tasks.Task<int> MyTestMethodAsync(int data) {
            return base.Channel.MyTestMethodAsync(data);
        }
    }
}
