//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReasignAddressesCAP32.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int MasterPortId { get; set; }
        public int SlavePortId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ProtocolId { get; set; }
    
        public virtual Port MasterPort { get; set; }
        public virtual Port SlavePort { get; set; }
    }
}
