//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReasignAddressesCAP32.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommandClass()
        {
            this.ElementTypes = new HashSet<ElementType>();
        }
    
        public int TagClassId { get; set; }
        public bool SelectBeforeExecute { get; set; }
        public Nullable<int> LinkedTagClassId { get; set; }
    
        public virtual TagClass TagClass { get; set; }
        public virtual TagClass TagClass1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementType> ElementTypes { get; set; }
    }
}
