//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReasignAddressesCAP32.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlPosition
    {
        public int LayoutId { get; set; }
        public int ControlId { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    
        public virtual Control Control { get; set; }
    }
}
