//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReasignAddressesCAP32.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TedisNetEntities : DbContext
    {
        public TedisNetEntities()
            : base("name=TedisNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<DeviceType> DeviceTypes { get; set; }
        public virtual DbSet<TagClass> TagClasses { get; set; }
        public virtual DbSet<Operand> Operands { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<ElementType> ElementTypes { get; set; }
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<Control> Controls { get; set; }
        public virtual DbSet<NodePosition> NodePositions { get; set; }
        public virtual DbSet<Node> Nodes { get; set; }
        public virtual DbSet<ControlPosition> ControlPositions { get; set; }
        public virtual DbSet<TagScale> TagScales { get; set; }
        public virtual DbSet<Command> Commands { get; set; }
        public virtual DbSet<CommandClass> CommandClasses { get; set; }
    }
}
