//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReasignAddressesCAP32.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElementType()
        {
            this.Elements = new HashSet<Element>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> SymbolId { get; set; }
        public Nullable<int> StateTagClassId { get; set; }
        public Nullable<int> StateCommandClassId { get; set; }
        public Nullable<int> ColorPropagationTypeId { get; set; }
        public Nullable<int> DialogActionId { get; set; }
        public Nullable<bool> IsExport { get; set; }
        public string Color1 { get; set; }
        public string Color2 { get; set; }
    
        public virtual TagClass TagClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Element> Elements { get; set; }
        public virtual CommandClass CommandClass { get; set; }
    }
}
