//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReasignAddressesCAP32.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Node()
        {
            this.NodePositions = new HashSet<NodePosition>();
        }
    
        public int Id { get; set; }
        public int NetworkId { get; set; }
        public int NodeTypeId { get; set; }
        public string Color { get; set; }
        public int RotationAngle { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> ElementId { get; set; }
        public string Description { get; set; }
    
        public virtual Element Element { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NodePosition> NodePositions { get; set; }
    }
}
